#!/bin/bash

echo "🔍 Verifying MTN MOMO Sandbox Configuration..."
echo ""
echo "Based on what we set:"
echo "✅ MTN_MOMO_ENVIRONMENT = sandbox"
echo "✅ MTN_MOMO_BASE_URL = https://sandbox.momodeveloper.mtn.com"
echo ""
echo "Your credentials:"
echo "  - Subscription Key: 79f94857e55d4e39a6ad327df309c0d1"
echo "  - API User: 686bed0f-9a72-4583-a1e4-a45efae86606"
echo "  - API Key: f8e81a0641c8466bacb1f5ceab6ed699"
echo ""
echo "📋 Sandbox Mode Characteristics:"
echo "  ✓ Uses sandbox.momodeveloper.mtn.com"
echo "  ✓ Test phone numbers: 237671234567 (success), 237671234568 (pending), 237671234569 (fail)"
echo "  ✓ No real money is charged"
echo "  ✓ Payments auto-approve in seconds for testing"
echo ""
echo "🚨 Production Mode Would Use:"
echo "  ✗ momodeveloper.mtn.com (no 'sandbox' subdomain)"
echo "  ✗ Real Cameroon phone numbers"
echo "  ✗ Real money transactions"
echo "  ✗ Requires MTN business verification"
echo ""
echo "✅ CONFIRMED: You are in SANDBOX MODE"
